[book]
authors = ["Open Component Model", "Piaras Hoban"]
language = "en"
multilingual = false
src = "src"
title = "MPAS Documentation"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
